### ISSUE TITLE
displays loading only

### ISSUE THREAD

**Issue by tim-digitised** [eouia/MMM-GoogleShoppingList#2]
Hey mate, trying this module out and I've got it loaded, but it only displays 'loading' and my list never shows-up. 

When I watch my pm2 logs, I can see the following error come out:
`mm > [GSL] Trying to login
mm > (node:4600) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Evaluation failed: TypeError: Cannot read property 'click' of null at __puppeteer_evaluation_script__:2:44`

**MM Version:** Current
**Node Version:** 9.11.2
**PM2 Version:** 3.2.2
**Chromium Version:** Version installed with current MM

Let me know if you need any other info.

Thanks

**Comment by eouia** [comment]
Hmmm.. I think you are using 2-Factor-Auth. There is no official API for Google ShoppingList, therefore, I'm using screen-scraping. It cannot be done with 2FA. Sorry.

**Comment by tim-digitised** [comment]
Hey Mate - Nah, not using 2FA... been troubleshootting the code and it can't find the #email selector you use because the ID has changed. 

Have you tried renaming your cookie file and attempting the login process again via the script?

**Comment by eouia** [comment]
Hmmm. My test has no problem currently. 
Would you test with 
```
{
          //disabled:true,
          module: "MMM-GoogleShoppingList",
          position: "top_right",
          header: "My Shopping List",
          config: {
            creds: {
              email: "xxxx",
              password: "xxxx",
            },
            useCookies: false,
            scanInterval: 1000*60,
            displayImage: false,
            browser: {
              headless: false
            }
          }
        },
```
With `headless:false` option, you can look what's going on.

**Comment by alexgaspard** [comment]
Hi, thanks for your work!
I got the same problem with these logs:
```
0|magicmir | (node:20805) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r599821
0|magicmir | (node:20805) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
With `headless:false` I got:
```
0|magicmir | (node:20510) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!
0|magicmir | TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
0|magicmir | (node:20510) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I updated chromium browser but same result, do you have an idea?

**Comment by eouia** [comment]
@alexgaspard
First. Which device & OS are you using? (e.g: RaspberryPI 3B+ / Raspbian Stretch)
Second, Where is your Chromium installed? (e.g: `/usr/bin/chromium-browser`)

For Second answer; Can you execute chromium in your shell? (e.g: `/usr/bin/chromium-browser http://google.com`)
If your chromium is installed in other directory, set config value 
```
 browser: {
      headless: true,
      executablePath: "YOUR CHROMIUM PATH"
}
```
Then try again.

**Comment by alexgaspard** [comment]
Hi thanks for your answer, here are my commands results:

**> cat /proc/device-tree/model**
`Raspberry Pi 2 Model B Rev 1.1`
**> uname -a**
`Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux`
**> cat /etc/os-release**
```
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
Chromium is at `/usr/bin/chromium-browser`

With:
**>  DISPLAY=:0 /usr/bin/chromium-browser http://google.com**
I got chrome launching google.com but I got these errors
```
bootstrap_helper: /usr/lib/chromium-browser/nacl_helper: Cannot open ELF file!  errno=2
[1:1:1104/151759.501039:ERROR:nacl_fork_delegate_linux.cc(315)] Bad NaCl helper startup ack (0 bytes)
[2826:2826:1104/151812.280127:ERROR:sandbox_linux.cc(343)] InitializeSandbox() called with multiple threads in process gpu-process.
```

I tried headless true or false, with true I can see chrome launching repeatedly with about:blank as url

**Comment by eouia** [comment]
@alexgaspard 
As Error messages said, There could be sandbox issue on some Chrome version.
https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

try to modify configuration with this;
```
browser: {
  ...
  args: ['--no-sandbox', '--disable-setuid-sandbox'], // <= this could make sandbox disabled.
}
```

If it would fail also, the only solution is to install Chromium with version r599821

**Comment by alexgaspard** [comment]
Thank you for your help.
Unfortunately it is not working either, I cannot find this version of chromium,  `sudo apt install chromium-browser=r599821` fails

**Comment by eouia** [comment]
Sorry, I cannot help about that. I suspect Raspbian Jessie has some missing dependencies.

**Comment by eouia** [comment]
I'll close this. If you have still problem, leave it here again.

**Comment by alexgaspard** [comment]
Ok thanks

Le dim. 11 nov. 2018 à 18:54, Seongnoh Sean Yi <notifications@github.com> a
écrit :
