### ISSUE TITLE
Empty Shopping list

### ISSUE THREAD

**Issue by 1975felix** [eouia/MMM-GoogleShoppingList#3]
Module was loading, but after few second of loading on the screen my shopping list is Always empty

**Comment by eouia** [comment]
Check whether is your “PRIME” list empty.

**Comment by 1975felix** [comment]
maybe the Language will be the problem? my prime list is called principale

**Comment by eouia** [comment]
I’m not sure. I need some test. Whuch language are you using? And tell me the items spell.

**Comment by 1975felix** [comment]
I use italian Language, the PRIME list is called "Principale" the title is "La mia lista della spesa" and the 2 items insert in list is "pane" and "latte" without ""

thank you

**Comment by eouia** [comment]
Let's check what is going behind the screen;
First, tell me whether `cookie.json` exists in your module directory. If module could login to service, it would be created automatically after running
In your module config(`config: { ... }`), add belows and tell me what's going on. 
```
config: {
    ...
    browser: {
      headless: false,
    },
   ...
}
```

**Comment by 1975felix** [comment]
cookie.json doesn't exist in module directory and only loading… on the screen when adding you code

**Comment by eouia** [comment]
Ok. If there is no `cookies.json`, it should be created after running. It means, Process of Login to ShoppingList page might have been failed.
And how about `headless: false`?, A window(maybe Chromium browser) should be opened on your MM during running. did it happen?
Last, Is there no other errors in log? You can see with `pm2 show log` or `npm start dev` (after termination of `pm2`)

**Comment by 1975felix** [comment]
with headless: false nothing on screen no Chromium window or other only loading…. but pm2 log shom me a strange error….

|MagicMir | 
0|MagicMir | (node:1982) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 16): Error: Failed to launch chrome!
0|MagicMir | /home/pi/MagicMirror/modules/MMM-GoogleShoppingList/node_modules/puppeteer/.local-chromium/linux-594312/chrome-linux/chrome: 1: /home/pi/MagicMirror/modules/MMM-GoogleShoppingList/node_modules/puppeteer/.local-chromium/linux-594312/chrome-linux/chrome: $##@@@�#�##�#�#�######��l#��l###�l#�l#�l#@A##@A#####@@@p#��t##���#: not found
0|MagicMir | /home/pi/MagicMirror/modules/MMM-GoogleShoppingList/node_modules/puppeteer/.local-chromium/linux-594312/chrome-linux/chrome: 1: /home/pi/MagicMirror/modules/MMM-GoogleShoppingList/node_modules/puppeteer/.local-chromium/linux-594312/chrome-linux/chrome: ELF####: not found
0|MagicMir | /home/pi/MagicMirror/modules/MMM-GoogleShoppingList/node_modules/puppeteer/.local-chromium/linux-594312/chrome-linux/chrome: 1: /home/pi/MagicMirror/modules/MMM-GoogleShoppingList/node_modules/puppeteer/.local-chromium/linux-594312/chrome-linux/chrome: Syntax error: end of file unexpected
0|MagicMir | 
0|MagicMir | 
0|MagicMir | TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
0|MagicMir | 

i have try to reinstall module but nothing happen

**Comment by eouia** [comment]
Ok. It seems Chromium for puppeteer not to be installed properly. 
Test this in your RPI.
```
/usr/bin/chromium-browser http://google.com
```
Is it opened?
Or you'd missed this;
```
sudo apt install chromium-browser
```

**Comment by Webse88** [comment]
Hello eouia,
I have the same problem. First the module says "Loading..." but after a few seconds this dissappears and there is just the header of the list, no content.  

I also have a file cookies.json but it is in /home/pi/MagicMirror
I also tried /usr/bin/chromium-browser http://google.com and it is showing the google page without problems. 

Do you have any other idea?
Thanks

**Comment by 1975felix** [comment]
If i try /usr/bin/chromium-browser http://google.com and it is showing the google page and also i have cookies.json in home/pi/MagicMirror at the same of other user Webse88.
I have try to format my microsd card and reinstall all MagicMirror and modules but same problem

**Comment by eouia** [comment]
@1975felix @Webse88 
I made an update. Could you try?

**Comment by 1975felix** [comment]
yes, now working.. Good job thank you

**Comment by naufalwaffl** [comment]
I followed all the code, ended up in config file error... and could not find cookies.json plz help!

**Comment by eouia** [comment]
@naufalwaffl If you have a config file error, it would be some syntax failure. Check your config file and fix your mistypo. Then try again.

**Comment by naufalwaffl** [comment]
found the error and solved it, now its stuck on loading continuously? what now? what am I missing?

**Comment by eouia** [comment]
@naufalwaffl 
It will be the same with https://github.com/eouia/MMM-GoogleShoppingList/issues/6 Sorry in that case, I have nothing to suggest.

**Comment by naufalwaffl** [comment]
Hmm ok thanks and I'm eagerly waiting
