### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by critterskins** [eouia/MMM-GoogleShoppingList#4]
I'm loving this module not sure if I should've asked here but is there a way to make the Grey label black or transparent please.

**Comment by eouia** [comment]
You can add this into your `css/custom.css`
```
.GSL_ITEM {
  background-color:unset; /* Or change to #000 */
}
```

**Comment by critterskins** [comment]
That's awesome thank you so much for your help.

**Comment by eouia** [comment]
No problem. I'll close this issue. Have a nice day.
