### ISSUE TITLE
keep loading

### ISSUE THREAD

**Issue by mattcasper** [eouia/MMM-GoogleShoppingList#6]
hello
i had this module running before with no issues
been trying several ways to make this work the past few day without any success
i reinstall many times, setup a new gmail account, started from a fresh custom.css and config.json file and the module doesn't show any data, just the loading page.
any suggestion?

**Comment by eouia** [comment]
This module using unofficial screen hoooking technic.
Sometimes Google change it's site structure per individual user temporaly. I think they tried something whatever.
Unfortunately, Unless that change be applied to all users, I cannot figure out what is changed and how to fix it.
So, currently there is no way to solve it. sorry.

**Comment by naufalwaffl** [comment]
im having the same problem, it would have a been brilliantly useful module otherwise, if you come up with a fix, plz let me know

**Comment by eouia** [comment]
I promise I'll fix this issue when the changes are fixed to all user. I'll close this issue. I wish good lucks to all us. 
Have a nice day.

**Comment by shahsaagar** [comment]
I installed the module but not sure why its showing loading.. 

Below is my js
		{
		  module: "MMM-GoogleShoppingList",
		  position: "bottom_right",
		  header: "My Shopping List",
		  config: {
			creds: {
			  email: "xxx@gmail.com",
			  password: "Password",
			},
			scanInterval: 1000*60,
			displayImage: false, //if you set, you can get image of items. but very ugly. I don't recommend.
		  }
		},

**Comment by eouia** [comment]
@shahsaagar 
I need error log for detail. But as I've wrote above, some user might not be able to use this module due to Google's user experiment.
