### ISSUE TITLE
Never stops loading

### ISSUE THREAD

**Issue by DuMees** [eouia/MMM-GoogleShoppingList#9]
Hi,

For some reason it never stops loading. Perhaps it is broken?

**Comment by jongov** [comment]
Same for me! It states that it fails to log and returns code 0.

**Comment by eouia** [comment]
Maybe or not. There is no official API for GoogleShopping List, so I should use crawling.  Google sometimes change their site structure for A/B test or any reason I cannot understand. Unfortunately unless the change be applied to all user, I cannot fix it. Sorry.

**Comment by gubastide** [comment]
Hi, 

I'm new on github and on Rpi ... 
I a installing Rpi to make the Magic Mirror and I would like to install Google Shopping List but I have the same problem ... It's installed and when I launch (npm start) I see the interface with the "Loading" but no more ... 
Can you help me ? 

Thank you !

**Comment by eouia** [comment]
Sorry, This module is not stable for all environments. Some could not get a result, but cannot solve. This module is experimental so can't help.

**Comment by gubastide** [comment]
Ok thank you for your answer !
